// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Jenny.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "Jenny.4b9eb8e4-c409-442b-932f-241cae3474b5";
        public const string Name = "Jenny";
        public const string Description = @"Jenny VS2022 x64 extension";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Simply Genius";
        public const string Tags = "";
    }
}
