// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Jenny.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJennyPackageString = "525d1a6f-8e30-4552-bee8-70f2922695a0";
        public static Guid guidJennyPackage = new Guid(guidJennyPackageString);

        public const string guidJennyRunAllCmdSetString = "905121e8-cabd-47f2-a4eb-6c2073f12363";
        public static Guid guidJennyRunAllCmdSet = new Guid(guidJennyRunAllCmdSetString);

        public const string guidJennyRunProjectCmdSetString = "600cd3fb-7954-4c18-a4ca-87825916a468";
        public static Guid guidJennyRunProjectCmdSet = new Guid(guidJennyRunProjectCmdSetString);

        public const string guidImagesString = "a5c3cda4-70a2-4dae-b8e8-8f8b73de0559";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RunAllMenuGroup = 0x0001;
        public const int cmdidJennyRunAll = 0x0101;
        public const int RunProjectMenuGroup = 0x0002;
        public const int cmdidJennyRunProject = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}