using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Jenny.MEF.Coder;

using Jenny.Core.Schema;

namespace Jenny.Coder.Internal
{
	partial class DbContextPerStatement
	{

		//-----------------------------------------------------------------------------------------
		// HeaderWarning

		const string HeaderWarning =
@"/****************************************************************/
/*                                                              */
/* This file is generated automatically and may be over-written */
/*                                                              */
/*               !!!  DO NOT EDIT THIS FILE  !!!                */
/*                                                              */
/****************************************************************/
";

		//-----------------------------------------------------------------------------------------
		// HeaderDOG

		string HeaderDOG( CoderConfig config, Model _ )
		{
			return HeaderWarning +
@"
#pragma warning disable IDE1006 // Naming Styles
#pragma warning disable IDE0049 // Simplify Names
#pragma warning disable CS8321 // Local function is declared but never used

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Linq.Expressions;

using NBootstrap.Global.DOG;

//------------------------------------------------------------------------------------------------------------------------------
// " + Marker_DOG + @"

namespace " + config.Namespace + @".DOG
{
	public class " + MarkerAttributeClass_DOG + @" : Attribute { }
}

//------------------------------------------------------------------------------------------------------------------------------
";
		}

		//-----------------------------------------------------------------------------------------
		// HeaderDAL

		string HeaderDAL( CoderConfig config, Model _ )
		{
			return HeaderWarning +
@"
using System;

namespace " + config.Namespace + @".DAL
{

	//------------------------------------------------------------------------------------------------------------------------------
	// " + Marker_DAL + @"

	public class " + MarkerAttributeClass_DAL + @" : Attribute { }

	//------------------------------------------------------------------------------------------------------------------------------
";
		}

		//-----------------------------------------------------------------------------------------
		// HeaderREP

		string HeaderREP( CoderConfig config, Model _ )
		{
			return HeaderWarning +
@"
#pragma warning disable IDE0049 // Simplify Names
#pragma warning disable IDE0063 // Use simple 'using' statement
#pragma warning disable IDE1006 // Naming Styles

using System;
using System.Collections.Generic;
using " + ( ( (int) config.DbContextBuild ) < 3 ? "System.Data.Entity;" : "Microsoft.EntityFrameworkCore;" ) + @"
using System.Linq;
using System.Runtime.CompilerServices;

using NBootstrap.Global;

namespace " + config.CoderSettings[ Settings.OUTPUT_NAMESPACE_REP ] + @"
{

	//---------------------------------------------------------------------------------------------
	// Hook delegate

	public delegate void HookHandler<T>(
		object sender,
		" + config.CoderSettings[ Settings.OUTPUT_CLASSNAME_REP ] + @" repo,
		global::" + config.CoderSettings[ Settings.OUTPUT_CLASSFULLNAME_LUT ] + @" token,
		T args,
		UpdateMap<T> map,
		UpdateMapEntryColumnBuilder<T> map2
	);

	//------------------------------------------------------------------------------------------------------------------------------
	// " + Marker_REP + @"

	public class " + MarkerAttributeClass_REP + @" : Attribute { }
";
		}

		//-----------------------------------------------------------------------------------------
		// HeaderCTX

		string HeaderCTX( CoderConfig config, Model _ )
		{
			return HeaderWarning +
@$"
using System;
{( config.DbContextBuild == MEF.Config.DbContextBuild.EFCore ? "" : "using System.Data.Entity;" )}

namespace " + config.Namespace + @".DAL.Context
{

	//------------------------------------------------------------------------------------------------------------------------------
	// " + Marker_CTX + @"

	public class " + MarkerAttributeClass_CTX + @" : Attribute { }

	//------------------------------------------------------------------------------------------------------------------------------
";
		}

		//-----------------------------------------------------------------------------------------
		// HeaderDDL

		string HeaderDDL( CoderConfig config, Model _ )
		{
			return HeaderWarning +
@"
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;

using System.Web.Mvc.Html;

namespace " + config.Namespace + @".DDL
{

	//------------------------------------------------------------------------------------------------------------------------------
	// " + Marker_DDL + @"

	public class " + MarkerAttributeClass_DDL + @" : Attribute { }

	//------------------------------------------------------------------------------------------------------------------------------
";
		}

		//-----------------------------------------------------------------------------------------


	}
}
