/****************************************************************/
/*                                                              */
/* This file is generated automatically and may be over-written */
/*                                                              */
/*               !!!  DO NOT EDIT THIS FILE  !!!                */
/*                                                              */
/****************************************************************/

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;

using System.Web.Mvc.Html;

namespace JennyDemo.DDL
{

	//------------------------------------------------------------------------------------------------------------------------------
	// Generated_By_Jenny_DDL

	public class Generated_By_Jenny_DDLAttribute : Attribute { }

	//------------------------------------------------------------------------------------------------------------------------------

	//-----------------------------------------------------------------------------------------------

}
